### ISSUE TITLE
[I5 Task 12] MCP high-level surface + thin Skill

### ISSUE THREAD

**Issue by nyangko** [nyangko/Brainprint#25]
# I5 Task 12 — MCP high-level surface + thin Skill

Parent roadmap: #20

Base commit: b1c04c0bbe8bfc19c699657286c1944cf162417d

This issue is the authoritative implementation Source of Truth for I5 Task 12.
Task 11 is complete. Do not start Task 13.

## Purpose

Expose the completed Task 10/11 Brainprint query surface to MCP-capable coding Agents through a small Agent-agnostic Level 1 surface, without moving Core truth or decision logic into the MCP adapter.

Target:

    Agent
      ↓ MCP stdio
    brainprint-mcp
      ↓ existing Task 11 local IPC / protocol v2
    brainprintd
      ↓
    CoreQuerySurface

The MCP process is a thin protocol adapter. It does not open engine databases, run parsers, read project source, rank evidence, resolve ambiguity, choose Working State, refresh indexes, or execute commands.

## Current baseline

- Task 10 high-level CoreQuerySurface complete.
- Task 11 local API / CLI complete and verified.
- daemon protocol v2 exposes Query / QueryAck.
- CLI/local API preserve currentness, coverage, source, continuation, delivery budgets and typed errors.
- no Brainprint MCP crate/server exists.
- no Brainprint Skill exists.
- repository-native CLAUDE.md currently describes CodeGraph/RTK; Task 12 does not replace its adoption policy. Task 13 owns active adoption/guard rollout.

## Locked scope

Task 12 implements:

1. one local stdio MCP server binary;
2. exactly four high-level MCP tools: brainprint.find, brainprint.inspect, brainprint.relations, brainprint.context;
3. JSON schema mapping onto existing Task 11 QueryRequest/QueryResponse;
4. tool-schema size/cost measurement;
5. one thin generic Brainprint Skill/instruction artifact;
6. MCP integration tests proving semantic parity with Task 11 local API.

Task 12 does not implement:

- brainprint.run or command execution (I6);
- Agent-specific hooks/plugins;
- pre-tool interception or redundant exploration guard;
- session-start/bootstrap enforcement or pre-selection steering;
- automatic native-tool blocking;
- TUI/Web UI;
- HTTP/remote MCP;
- auth/OAuth;
- new Core query semantics;
- new database/schema/index;
- auto init/sync/rebuild/repair.

## MCP SDK / Rust compatibility decision

Brainprint workspace currently declares rust-version = 1.85.

Do not raise project MSRV solely for Task 12.

Use the official Model Context Protocol Rust SDK rmcp from its stable 1.x line that compiles with the existing Rust 1.85 workspace. Initial locked target:

    rmcp = 1.6.x
    features: server, macros/schemars as needed, transport-io

Do not use rmcp 3.x in this task if it requires raising the workspace MSRV.
The dependency is pinned through Cargo.lock. No git dependency.

If selected 1.6.x unexpectedly fails under the actual Rust 1.85 toolchain, stop and record the dependency/MSRV conflict here before changing MSRV or SDK family.

## Transport

MCP transport for P0 is stdio only.

Binary:

    brainprint-mcp

Rules:

- stdin/stdout belongs exclusively to MCP protocol;
- diagnostics go to stderr;
- no HTTP/TCP listener;
- no daemon embedding;
- no auto-start of brainprintd;
- daemon unavailable -> typed MCP tool failure with compact actionable message.

## Crate boundary

Add one workspace member:

    crates/mcp

Expected dependency direction:

    brainprint-mcp -> brainprint-core + rmcp/serde/serde_json/schemars/tokio as needed

brainprint-mcp must not depend on brainprint-engine.
brainprint-mcp should not depend on brainprint-daemon merely to reuse private client helpers.
It talks to brainprintd using the public brainprint-core::protocol Task 11 local IPC contract, as brainprint-cli does.
A small MCP-local connection helper is acceptable. Do not create a new shared client crate in Task 12 unless duplicate protocol code materially blocks correctness.

### brainprint.find

Modes: target, files, text.

Mapping:

    target -> Task 11 Find::Target
    files  -> Task 11 Find::Files
    text   -> Task 11 Find::Text

Text remains explicit. A target miss never automatically invokes text search.
No path/UUID/name guessing.

### brainprint.inspect

Maps directly to Task 11 Inspect.
If CurrentSource is delivered, return it exactly; never path/line only.

### brainprint.relations

Modes: direct, impact.

Mapping:

    direct -> Task 11 Relations
    impact -> Task 11 Impact

Direct remains one-anchor, one-hop, unpaged, no source. RESULT_TOO_LARGE stays explicit.
Impact uses the existing closed ChangeKind vocabulary. MCP does not choose a change kind.

### brainprint.context

Modes:

    change
    resume
    rules
    work_items
    lineage
    handoffs
    structure
    status

Mapping:

    change     -> Task 11 Context::Change
    resume     -> Task 11 Context::Resume
    rules      -> Task 11 Knowledge::Rules
    work_items -> Task 11 Knowledge::WorkItems
    lineage    -> Task 11 Knowledge::Lineage
    handoffs   -> Task 11 Knowledge::Handoffs
    structure  -> Task 11 Structure
    status     -> existing daemon Status request

This grouping reduces MCP tool-definition count without merging Core semantics.
status returns only daemon/runtime status already owned by the existing Status response; no fabricated Workspace health/freshness.

## Tool input design

Do not copy the entire Task 11 QueryRequest schema into every tool.
Each tool exposes only fields relevant to its modes while mapping bijectively to the existing wire request.

Common optional correlation fields:

    client_id
    session_id
    external_task_id
    external_subtask_id

Workspace selector:

    workspace_path OR workspace_id

Exactly one logical selector after normalization. If neither is supplied, the MCP process may use its startup working directory as workspace_path.
Never guess among registered Workspaces.

Role/team/persona are not authority and are not required in the P0 MCP schema.

## Budget contract

MCP must not invent hidden semantic budgets.

For planner-backed modes expose required:

    budget_profile: compact | standard | wide

Profiles map exactly to Task 11:

    compact  = 16 items / 16 KiB
    standard = 64 items / 64 KiB
    wide     = 128 items / 128 KiB

Optional max_items/max_bytes overrides are allowed.
No token cap in Task 12.

Text mode separately exposes:

    search_budget_profile: compact | standard | wide

mapping exactly to Task 11 SearchBudget profiles.
MCP never auto-enlarges a budget after BUDGET_TOO_SMALL.

## Retention / acknowledgement

MCP tool calls reuse Task 11 Query / QueryAck.

Safe P0 default:

    retention = disabled

unless the request explicitly supplies a stable Brainprint client_id or session_id and the adapter has reliable evidence the receiving Agent context is retained.

Do not infer retained-context safety from MCP process lifetime, client name, tool connection lifetime, role/team, or stdio connection alone.

The MCP process sends Task 11 QueryAck after it has successfully received and decoded the daemon QueryResponse. This acknowledges daemon -> MCP-client delivery. With ReuseDisabled it does not claim that the Agent retained reusable payload context.

Do not add a second ledger or acknowledgement protocol.
Task 13 may later connect retention/reset semantics to actual Agent session/adoption events.

## MCP result contract

Return structured MCP content whose semantic payload is the Task 11 QueryResponse result.
Do not stringify Debug output.

Preserve where applicable:

- target resolution;
- currentness;
- coverage/gaps;
- ambiguity candidates;
- source evidence;
- truncation;
- more_available;
- continuation;
- typed QueryError code/details;
- structure/knowledge/relations ordering.

MCP-specific wrapper metadata may include tool, mode, protocol_version and schema_version, but never changes Brainprint truth.
A small deterministic text summary is optional; structured content remains authoritative.

## Error mapping

Keep three layers distinct:

1. MCP protocol/server error: malformed MCP call or MCP server internal failure.
2. Brainprint local transport error: daemon unavailable, protocol v2 mismatch, local IPC failure.
3. valid Brainprint QueryOutcome::Err: NOT_INITIALIZED, WORKSPACE_AMBIGUOUS, INVALID_REQUEST, BUDGET_TOO_SMALL, CONTINUATION_MISMATCH, RESULT_TOO_LARGE, etc.

Do not collapse valid Brainprint typed query errors into generic MCP internal error.
Raw SQLite/driver/backtrace text remains forbidden.

## Continuation

Continuation passes through unchanged as the structured Task 11 continuation object.
No CLI base64 token inside MCP.
No MCP-side cursor/session map.
No automatic follow-up paging.

## Thin Skill

Add one canonical generic source:

    integrations/brainprint/SKILL.md

This is a repository artifact, not an Agent-specific installed path. Task 13 may later install/link it into client-specific locations.

The Skill contains only:

- Brainprint is preferred for project facts when available/current;
- find = location/files/explicit text;
- inspect = exact source/understanding;
- relations = direct dependency/impact;
- context = change/resume/rules/history/structure/state;
- do not repeat Read/Grep/Glob/shell discovery for facts Brainprint already returned current/complete;
- native fallback allowed when Brainprint says partial/stale/unsupported/ambiguous or user explicitly requests raw/native verification;
- editing remains the Agent's job;
- brainprint.run does not exist yet.

The Skill must not contain freshness state machine, precedence, privacy filtering, projection ranking, budget algorithms, schema dumps, full project Policy/Decision/Working State, long MCP manual, or client-specific hook instructions.

Operational content is concise natural English-first.
Do not inject presentation instructions; presentation default is zero unless user-registered preference is already returned by Core.

## Native instruction boundary

Task 12 does not rewrite repository CLAUDE.md adoption policy.
Task 13 owns adoption/bootstrap/guard rollout.
If Task 12 needs a native-instruction example for acceptance, keep it as a small fixture/snippet under the Task 12 integration/test area, not an always-on CLAUDE.md/AGENTS.md policy.

## Schema/token economy

Tool definitions themselves are product cost.

At build/test time serialize exact four tools/list definitions and record:

    tool_count
    total_schema_bytes
    per_tool_schema_bytes
    total_description_bytes
    per_tool_description_bytes

Record exact token count only when an exact tokenizer for a named benchmark model is present.
Otherwise:

    schema_tokens = NOT_MEASURED

Never estimate tokens from chars/bytes.

Also generate an explicit comparison fixture for a mechanically split one-tool-per-Task10-operation surface and compare exact schema bytes. Do not claim provider token savings without exact provider tokenizer measurement.

## No Agent-side deterministic cleanup

MCP output ordering is inherited from Core/Task 11.
The Skill must not tell the Agent to re-sort, dedupe, group, trim, or aggregate Brainprint results that Core already prepared.

## Security/locality

P0 MCP is local stdio only and talks to the local brainprintd endpoint.
No remote network, OAuth/auth server, privilege expansion, environment/secret indexing.
MCP client identity is diagnostic/correlation only, not authorization.

### Build/protocol

1. brainprint-mcp builds as a workspace binary.
2. starts on stdio without protocol-invalid stdout.
3. MCP initialize + tools/list succeeds with a real MCP client fixture.
4. exactly four Brainprint tools are exposed.
5. daemon unavailable -> compact typed tool failure, no panic.
6. daemon protocol mismatch remains explicit.
7. MCP server never starts/embeds brainprintd.

### Tool semantic parity

For a populated representative Workspace compare MCP structured payload to Task 11 local API payload after removing only MCP wrapper fields:

8. find target parity.
9. find files parity.
10. find explicit text parity.
11. inspect parity including CurrentSource.
12. relations direct parity.
13. relations impact parity.
14. context change parity.
15. context resume parity.
16. context rules parity.
17. context work_items parity.
18. context lineage parity.
19. context handoffs parity.
20. context structure parity.
21. context status parity with daemon Status.

No adapter-side reordering/normalization just to make parity pass.

### Error/currentness behavior

22. NOT_INITIALIZED stays typed.
23. WORKSPACE_AMBIGUOUS stays typed and never first-match.
24. incomplete/partial/stale/ambiguous remains distinguishable.
25. BUDGET_TOO_SMALL stays typed.
26. CONTINUATION_MISMATCH stays typed.
27. RESULT_TOO_LARGE stays typed.
28. Text is never automatic fallback.

### Economy/source behavior

29. MCP adapter performs zero project source reads.
30. MCP adapter performs zero DB queries directly.
31. no semantic backend starts because of MCP adaptation.
32. inspect source bytes equal Task 11 result.
33. grouped tool schemas measured exactly in bytes.
34. schema_tokens exact or NOT_MEASURED, never estimated.

### Skill

35. integrations/brainprint/SKILL.md exists.
36. Skill contains Brainprint-first substitution + safe fallback.
37. Skill contains no Core freshness/precedence/privacy/budget algorithms.
38. Skill does not present brainprint.run as available.
39. Skill injects no presentation instruction by default.
40. Skill size recorded.

### Boundary/regression

41. no Task 13 guard/hook/plugin code.
42. no I6 run/command execution.
43. no HTTP MCP server.
44. no engine/DB dependency from brainprint-mcp.
45. schema versions remain global v4 / project v4 / workspace v5 / index v10.
46. no SQL/migration/index.
47. Task 5–11 suites pass unchanged.
48. focused Task 12 MCP suite passes 5 consecutive runs.
49. fmt/clippy/build clean.

## MCP client compatibility validation

P0 acceptance must run stdio against:

- official/rmcp MCP client test fixture;
- one real installed MCP-capable coding client when available in the implementation environment.

Record exact client name/version tested.
Do not claim Claude/Codex/Gemini compatibility solely because protocol fixture passed.
If no real coding client is available, record NOT TESTED.

Task 13 owns stronger per-client adoption behavior.

## Performance/overhead record

For representative calls record:

    MCP input JSON bytes
    MCP structured-result bytes
    daemon Query request bytes
    daemon Query response bytes
    adapter-added bytes
    tools/list schema bytes
    Skill bytes
    latency: MCP total / daemon query / adapter overhead where measurable

Do not claim token savings from byte counts.
No full materialization solely for telemetry.

## Expected storage impact

    new SQL: none
    schema migration: none
    index: none

If Task 12 requires SQL/schema/index, stop and amend this issue before implementation.

## BLOCKED conditions

Stop before implementation if any becomes necessary:

- changing Task 10/11 truth semantics;
- changing protocol v2 only to make MCP easier;
- hidden ranking/precedence/currentness logic;
- adapter source reads or DB reads;
- Agent-specific hook/plugin or pre-tool/pre-selection guard;
- brainprint.run/command execution;
- automatic context bootstrap/Text fallback/WorkItem choice/init/sync/rebuild/repair;
- HTTP/TCP MCP;
- raising workspace Rust MSRV solely for latest MCP SDK without explicit design amendment;
- second delivery ledger/pager/continuation engine;
- tool output dropping Core uncertainty/status fields;
- Skill copying long Core/project rules.

## Validation

    cargo fmt --check
    cargo clippy --workspace --all-targets --locked -- -D warnings
    cargo test --workspace --locked
    cargo build --workspace --locked

Run focused Task 12 MCP tests 5 consecutive times.

## Completion record

On success append directly to this issue body:

    commit SHA
    files/modules changed
    rmcp version / MCP protocol version tested
    Rust/MSRV result
    four tools + exact modes
    daemon/local API mapping
    retention/ack behavior
    continuation behavior
    typed error behavior
    direct Task11 vs MCP semantic parity matrix
    source reads / DB reads / backend starts/requests
    tools/list schema byte measurements
    token measurement or NOT_MEASURED
    Skill path/bytes/rules summary
    representative byte/latency measurements
    real MCP clients tested + versions
    schema versions
    SQL/migration/index changes
    workspace tests
    focused suite x5
    fmt/clippy/build
    known limitations
    design conflicts
    confirmation Task 13 not started

No comments. Update issue body only.

## Final invariant

    Agent with generic MCP support
      -> four small Brainprint tools
      -> thin MCP adapter
      -> Task 11 protocol v2
      -> exactly the same Core truth

    Skill teaches when to use Brainprint;
    Skill/MCP never decides what is true.
